version: "3.9"
services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: doctor_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
  app:
    build: .
    depends_on: [db]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mysql://db:3306/doctor_db?useSSL=false&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "8080:8080"
volumes:
  dbdata:
