version: "3.9"
services:
  db:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: doctors_dev_db
    ports:
      - "3307:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
  app:
    build: .
    depends_on: [db]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mysql://db:3307/doctors_dev_db?useSSL=false&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "8080:8080"

